#!/usr/bin/env node

"use strict";
if (process.argv.length < 3) {
  console.log("usage: sendSpam your@email.address")
  process.exit(-1)
}

var emailAddress = process.argv[2]

var fs        = require('fs')
var email     = fs.readFileSync('email.html')
var _         = require('lodash')
var Promise   = require('bluebird')
var mailer    = require('nodemailer')
var Store     = require("jfs")
var db        = new Store("data", { pretty: true })
var sentList  = db.getSync("sent") || []

// email setting
var smtpConfig = {
    host: 'smtp.gmail.com',
    port: 465,
    secure: true, // use SSL
    auth: {
      user: process.env.GMAIL_ACCOUNT,
      pass: process.env.GMAIL_PASSWORD
    }
}
var transporter = Promise.promisifyAll(mailer.createTransport(smtpConfig))
var mailOptions = {
  from: '"Jonghun Yu" <jonghun.yu@nerdyfactory.com>', // sender address
  to: '', // list of receivers
  subject: 'Hi I\'m Jonghun Yu from nerdyfactory', // Subject line
  html: email
}


function sendEmail(address) {
  mailOptions.to = address
  return transporter.sendMailAsync(mailOptions)
    .then((info, error) => {
      if (error) {
        console.log(error)
        return null
      }
      console.log('Message sent: ', address, info.response)
      return address
    })
}

sendEmail(emailAddress)
.then((email) => {
  return db.saveSync("sent", _.union([email], sentList))
})
